rope/refactor/extract.py, ropetest/refactor/extracttest.py
This should fix https://github.com/python-rope/rope/issues/102. I've added three test cases which test my original problem and then also two variants on that where the extraction should actually add another read parameter and one where the `else` case of the loop reads variables.
Now I've implemented this by looking at that file, but really, if you can suggest anything to clean it up I'd be very grateful.
=> Fix extract method with list comprehension.

rope/refactor/patchedast.py, ropetest/refactor/patchedasttest.py
This fixes a specific bug I had where I could not use extract_method feature if the code being extracted had a set or dict comprehension.  This was due to patched_ast not adding region information to anything in those parts of the ast and so the code could not be reconstructed.
=> add support for DictComp and SetComp to patched_ast

docs/overview.rst
The default value in the Inline Parameter example was 1, and when using Inline was passing 2.
=> Wrong parameter default value in Inline Parameter

README.rst
'Cos this project is already at github.com/python-rope/rope
=> Remove note about project moving to python-rope/rope

rope/base/codeanalyze.py, ropetest/codeanalyzetest.py
Hello,
I had an issue with rope crashing or giving truly bizarre results when moving/renaming specific modules, which I tracked down to how rope parses the source files. Any file which contains a multiline string that starts with more than 3 quote characters would cause it to incorrectly compute the logical line numbers for each scope. I've adjusted the RE which is used to delimit scopes and added some new tests for this case.
For example, `""""Hello, world!" example."""` is a valid python string that rope does not handle correctly.
=> Bugfix for parsing strings with extra quote characters

rope/refactor/importutils/module_imports.py, ropetest/refactor/importutilstest.py, ropetest/refactor/movetest.py
If there are import statements already at the top of the module, replace
the imports at the same position. This changes the notion of "first
import line" in the case when the module has an existing import as
the first statement after the docstring (if any).
=> Preserve whitespace before the first import statements

CONTRIBUTORS, docs/overview.rst, docs/rope.rst, rope/base/oi/docstrings.py, rope/base/oi/soi.py, ropetest/__init__.py, ropetest/docstringstest.py
Similar solutions:
- https://www.jetbrains.com/pycharm/help/type-hinting-in-pycharm.html
- https://www.python.org/dev/peps/pep-0484/#type-comments
- http://www.pydev.org/manual_adv_type_hints.html
- https://jedi.readthedocs.org/en/latest/docs/features.html#type-hinting
Discussions:
- https://groups.google.com/d/topic/rope-dev/JlAzmZ83K1M/discussion
- https://groups.google.com/d/topic/rope-dev/LCFNN98vckI/discussion
Tested in unittest (integration) and doctests (utils).
=> Hinting function params, function return value, class attribute using function/class docstrings or PEP-0484 comments.

setup.py
OK, if I want to make some development on rope I really want ``setuptools`` here (and ``develop`` command). Unless @aligrudi has strong objections, I will merge this into ``devel`` branch.
The only real objection I have heard about it is in http://thread.gmane.org/gmane.comp.python.rope/552/focus=556 which makes a vague statement about "Windows ready made installers" (I am not sure what he was talking about; ``rope`` is used by Python developers who are supposed to be able to use ``pip`` or ``python setup.py``).
@emacsway , @sergeyglazyrindev, any comments?
=> Switch to setuptools (`develop` command is kewl).

rope/base/default_config.py, rope/refactor/importutils/__init__.py, ropetest/refactor/movetest.py
Rope seemed to always choose the normal import by default, but this
leads to ugly code when the module is deeply nested in pacakges. This
option gives preference to the "from pkg import mod" style from-import.
Ex, when moving `mod1.do_something` to `pkg.mod2`
Before:
`mod3.py`:
```python
import mod1
mod1.do_something()
```
After [`prefer_module_from_imports = False`]:
`mod3.py`
```python
import mod1
import pkg.mod2
pkg.mod2.do_something()
```
After [`prefer_module_from_imports = True`]:
`mod3.py`
```python
import mod1
from pkg import mod2
mod2.do_something()
```
=> Add an option to prefer "from pkg import mod" imports

rope/refactor/move.py, ropetest/refactor/movetest.py, ropetest/refactor/multiprojecttest.py
Previously only fully-qualified imports of the name are removed, but
this potentially leaves leaves module imports that were only imported
for the name. This patch removes unused imports of the module that
previously contained the name as well.
Ex, moving `mod1.do_something` to another module
Related modules that depend on this function:
```python
from mod1 import do_something  # current implementation will remove
import mod1                    # current implementation will keep
from pkg import mod1           # current implementation will keep
```
I think that `import mod1` or `from pkg import mod1` should also be
removed if they are unused after the global is moved.
Note that this does not affect imports of other modules; only imports
of the name which is being moved or the module …
=> Remove all relevant unused imports when moving globals

rope/refactor/move.py
Don't make assumptions about the pyname until exceptional conditions are
checked. Previously, if the name was just a variable (not a class or function)
initializing the class would raise an AttributeError (not RefactoringError).
```
File "/third_party/py/rope/refactor/move.py", line 206, in __init__
self.old_name = self.old_pyname.get_object().get_name()
AttributeError: 'PyObject' object has no attribute 'get_name'
```
=> Check exception conditions before using pyname in move_global

rope/base/default_config.py
As config.py gets created in the project root, flake8 will, if enabled,
will find it and complain about style violations.
Ignoring .ropeproject in setup.cfg would introduce Rope-specific noise
in every affected project.
=> Disable flake8 in default config

rope/refactor/move.py, ropetest/refactor/movetest.py
This is a refactoring I really find useful, most often in the case of constants which are defined in some file that need to be moved elsewhere. Rope already supports this type of refactoring for functions and classes, but variables are a bit more tricky due to the lack of "def" or other declaration.
This implementation takes a simple approach to move the definition location of a global variable from one module to another, extending the MoveGlobal refactoring. See the added tests for examples.
Please let me know what you think! This case isn't as simple as the others, but I think there's a lot of value in supporting it at least to some degree.
=> Support moving global variables with move_global

rope/refactor/move.py, ropetest/refactor/movetest.py
It is common to prefix globals with a comment, e.g. for disabling lint
warnings, TODOs, etc. These should be moved along with the source by
move_global.
=> Include comment lines preceding definition in move_global

rope/refactor/move.py
This is an improvement to further specify that any import which would be
examined is one of the following forms (when moving pkg.module.SomeClass):
```python
from pkg import module
from pkg.module import any_name
import pkg.module
```
previously this would have also possibly matched
```python
from pkg import unrelated_module
```
even though this module is not affected.
=> Increase scrutiny on import filter to avoid removing unrelated imports

rope/refactor/move.py, ropetest/refactor/movetest.py
This only half-worked, and led to the imports being inserted between the
comment prefix and the global which was moved, which actually led to the
comment being removed from the destination. Added test for this scenario
and some extra processing on import insertion to preserve the comment
prefix.
This fixes a bug introduced in #177.
=> Patch for moving comment prefix on global names

rope/base/codeanalyze.py
Handle an escaped backslash at the end of a string to not mean an
escaped quote. This is a bugfix, but ideally this should not rely on RE
to parse the python syntax (this is very hard to get right).
Fixes #180.
=> Fix token matching RE used to determine line starts

rope/refactor/importutils/module_imports.py, ropetest/refactor/importutilstest.py
This previously would leave the old import in place because it is
readonly; really it shouldn't even touch these imports if they are
supposed to be filtered.
=> Don't split imports which are not matched by the filter

docs/overview.rst, rope/base/builtins.py, rope/base/oi/type_hinting/evaluate.py, rope/base/oi/type_hinting/factory.py, rope/base/oi/type_hinting/interfaces.py, rope/base/oi/type_hinting/providers/composite.py, rope/base/oi/type_hinting/providers/docstrings.py, rope/base/oi/type_hinting/providers/inheritance.py, rope/base/oi/type_hinting/providers/interfaces.py, rope/base/oi/type_hinting/providers/pep0484_type_comments.py, rope/base/oi/type_hinting/resolvers/composite.py, rope/base/oi/type_hinting/resolvers/interfaces.py, rope/base/oi/type_hinting/resolvers/types.py, rope/base/oi/type_hinting/utils.py, rope/base/pyobjectsdef.py, ropetest/type_hinting_test.py
Added parser for type-comments and docstrings, added support for the following syntax:
- Foo
- foo.bar.Baz
- list[Foo] or list[foo.bar.Baz] etc.
- set[Foo]
- tuple[Foo]
- dict[Foo, Bar]
- collections.Iterable[Foo]
- collections.Iterator[Foo]
Nested expressions also allowed:
- collections.Iterable[list[Foo]]
=> #186 preparation for support of typing module.

rope/base/default_config.py, rope/refactor/importutils/module_imports.py, ropetest/refactor/importutilstest.py
Rope, by default, rewrites import statements by removing all the
top-level import lines from the file, then sorting them, then
reinserting them at the top. This behavior of pulling everything to the
top of the file can be undesirable. As an alternative, we can rewrite
the imports in place, which won't sort them, but also won't impose this
extra constraint that all top-level imports must be at the top.
=> Add an option to disable sorting imports entirely

rope/base/pyobjectsdef.py, ropetest/refactor/renametest.py
This includes a basic unit test, though it might be good to extend all of the
current function rename tests to test async as well.
=> Added support for `async def`.

rope/base/stdmods.py, ropetest/builtinstest.py
=> Treat timemodule.so as a special case for Fedora python2

rope/refactor/patchedast.py, ropetest/refactor/patchedasttest.py
In a Call, these rules apply:
* positional args must come before keywords
* `*args` must come after all positional args
* `**kwargs` must come last
Fixes #203.
=> Fixed patchedast bug parsing *args

rope/base/default_config.py
default_config.py is written in to .ropeproject within projects using
rope.  This can cause linting checks for the project to start failing
due to the PEP-8 errors that are fixed herein.
These fixes were based on errors reported by pycodestyle (née pep8).
=> Fix PEP-8 errors in rope/base/default_config.py

rope/base/evaluate.py, rope/base/worder.py, ropetest/refactor/renametest.py
This case wasn't being handled correctly; e.g, the pyname for "foo" in
`import foo as bar` evaluates to an `AssignedName` instead of an
`ImportedModule`. This is similar to the module name in a "from" import,
adding a special case to handle it in the same way.
Fixes #229
=> Bugfix for detecting pynames in aliased import statements

rope/base/worder.py, ropetest/refactor/inlinetest.py
When inlining `a_func`
```python
def a_func(param1, param2, param3):
param2.name
a_func(2 <= 1, item, True)
```
the current result is `True.name`.
This is because the `2<= 1` argument is treated as a keyword argument and so the `True` argument becomes `param2`
This PR includes a fix to worder so it understands comparisons are not keyword arguments
=> When inlining function allow comparisons in arguments

rope/refactor/extract.py, ropetest/refactor/extracttest.py
If similar regions are found during extract method that overlap, the refactored code is invalid
For example, if the first two lines of `func` are extracted
```python
def func(p):
a = p
b = a
c = b
d = c
return d
```
the following is produced
```python
def func(p):
b = new_func(p)c = new_func(a)d = new_func(b)
b = new_func(p)
d = new_func(b)
return d
def new_func(p):
a = p
b = a
return b
```
With this PR a correct refactoring is performed
```python
def func(p):
b = new_func(p)
d = new_func(b)
return d
def new_func(p):
a = p
b = a
return b
```
=> Avoid overlapping regions when extract similar=True

rope/base/oi/doa.py, rope/base/oi/runmod.py, rope/base/project.py, ropetest/__init__.py, ropetest/doatest.py
Before unpickling anything, ensure that it has a valid digital
signature using a randomly-generated shared key. In order for an attacker
to send or tamper with data on the same socket, they must know this key
to compute a valid signature.
Fixes #105 by requiring some authentication before unpickling.
=> Perform signature verification on pickled data transferred over sockets

rope/__init__.py, setup.py
I have this bug report in [email](https://groups.google.com/d/msg/rope-dev/afB5KgNhSvk/zkubyRUZAwAJ):
```
OS: windows 10
Python: 3.6.7
When I install rope, I have this error: 
Collecting rope
Using cached 
https://files.pythonhosted.org/packages/af/9b/e92c1d561631da9fbeaf4d5d67ecb65b7d284a63069ee37aec44a2eefae4/rope-0.12.0.tar.gz
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "<string>", line 1, in <module>
File 
"C:\Users\abukreev\AppData\Local\Temp\pip-install-jve2b1hl\rope\setup.py", 
line 13, in <module>
import rope
ModuleNotFoundError: No module named 'rope'
```
I agree that importing too much in setup.py is a bad idea.
What do you think?
=> Setup version

rope/base/codeanalyze.py, rope/base/utils/pycompat.py, rope/refactor/occurrences.py, ropetest/refactor/renametest.py
Adds support for renaming variables in PEP-498 f-strings for Python >= 3.6, using the `ast` module to parse f-strings while searching for occurrences of the variable. This resolves #226.
=> Rename variables in f-strings

rope/base/builtins.py, ropetest/pycoretest.py
When __enter__ is called within a 'with' expression, wrap the
return value with a pyobject instead of returning 'File' directly.
This will keep us consistent with existing functionality
=> Fix return value of __enter__ for builtin File

rope/base/ast.py, rope/base/oi/type_hinting/utils.py, rope/base/utils/datastructures.py, rope/base/utils/pycompat.py, ropetest/type_hinting_test.py
This is an attempt to fix #247, but still unsuccesful.
@soupytwist , any idea, what's going on? I have tried to replace ``threading.Thead.isAlive`` (which has been deprecated and unnecessary since 2.6) with ``.join`` (which I guess will never be deprecated), but still doesn’t seem to work. Why rope doesn’t suggest it?
=> 247 is alive completion

rope/base/codeanalyze.py, ropetest/codeanalyzetest.py
These are the changes to fix the bug described at [issue 288](https://github.com/python-rope/rope/issues/288) . It is passing all the tests and also solving the issue. Could you take a look at it please?
=> get_string_pattern_with_prefix short str pattern modified

rope/base/pyobjects.py
=> ast.Str and other constants are deprecated since 3.8.

rope/base/pynames.py, rope/base/pyobjectsdef.py, rope/base/utils/__init__.py, ropetest/contrib/codeassisttest.py
This PR changes `get_definition_location()` to point to the line where the class/function is defined rather than pointing to the decorator. This makes older versions match Python 3.8's more correct behaviour.
Note that this is a backwards incompatible change if someone depends on `get_definition_location()` pointing to the decorator.
Note: this PR also contains commits from https://github.com/python-rope/rope/pull/306, you most likely would want to review the diffs just from this branch to that one rather than seeing both changes simultaneously.
=> Fix get definition location for Python 3.8

rope/base/codeanalyze.py, ropetest/codeanalyzetest.py, ropetest/contrib/codeassisttest.py
Fix the linked issue #248. 
This issue is because the three single quotes here: `p = 'foo'''` is misrecognised as a triple-quoted string, which is not consistent with how Python interprets it as an opening and closing of single-quoted string.
=> #248 fix false triple quoted string

rope/refactor/patchedast.py, ropetest/refactor/extracttest.py, ropetest/refactor/patchedasttest.py
Fixes #282. This PR adds dictionary unpacking syntax:
{**a, **b}
to patchedast and allows refactoring to include lines which contains constructions with this syntax.
=> #282 Implement PEP-448 generalized dict-unpacking

rope/refactor/patchedast.py, ropetest/refactor/extracttest.py, ropetest/refactor/patchedasttest.py
Closes #313. This implements patchedast and extract refactoring for code that contains f-string.
The region matching is a bit dodgy with implicitly joined strings that has a mixture of f-string and regular string and probably other corner cases as well, owing to how the ast doesn't seem to provide an easy way to find the offsets of formatted values without writing a full fledged string expression parser, but it works well enough for most other situations.
=> Implement f-string extract refactoring

rope/base/evaluate.py, ropetest/refactor/renametest.py
This PR fixes #317. 
This fixes the error:
'NoneType' object has no attribute '_fields'
when renaming variable that contains dict with generalized unpacking.
=> Fixes #317. Improve handling of generalized dict unpacking during dict rename

rope/base/pyobjectsdef.py, ropetest/pyscopestest.py, ropetest/refactor/renametest.py
This PR implements renaming variables assigned by inline assignment expression (a.k.a. walrus operator/`:=`) and the looping variables of list/set/dict/generator comprehension.
This also solves point 3 from [my comment on #249](https://github.com/python-rope/rope/issues/249#issuecomment-718248829). The variable scoping for list comprehension does not follow Python 3 semantic, but as mentioned there, fixing the scopes likely will require a significant rewrite of the scope finding mechanism.
=> Implement renaming of walrus operator and loop variables in comprehensions

rope/base/evaluate.py, rope/refactor/extract.py, ropetest/refactor/extracttest.py, ropetest/refactor/renametest.py
Fix issue in #114 where extracting code that writes to global variables or contains augmented assignments produces refactored code that doesn't behave the same as the original code.
=> Fix #114. Extract augmented assignment

rope/base/evaluate.py, ropetest/refactor/renametest.py
#319 introduced some changes in dict-unpacking, but the implementation causes some tests to fail in Python 2.7 because the implementation uses constructs that aren't correct in Python 2.7. This fixes those failing tests.
=> Fix test and handling of dict rename in Python 2.x

rope/refactor/patchedast.py, ropetest/refactor/extracttest.py, ropetest/refactor/patchedasttest.py
Also found missing _NamedExpr node, but can't fidure out how to implement it
I'm trying to fix #326 
As I can see, it works: Rename works in both sides of `:=` operator
=> Added _NamedExpr into `patchedast.py`

rope/contrib/generate.py, ropetest/contrib/generatetest.py
I'm working on option generating class in different file in ropevim. RopeVim uses "create_generate" function, it doesn't provide option to set "goal_resource".
I added this to rope. It will be nice if this can be merged. Thanks ;)
=> create_generate with goal_resource param

.github/workflows/main.yml, rope/base/evaluate.py, rope/base/oi/soa.py, ropetest/refactor/patchedasttest.py
The ast module in Python 3.9 has some API changes. Quoting [1]:
> Simplified AST for subscription. Simple indices will be represented by their value, extended slices will be represented as tuples.  Index(value) will return a value itself, ExtSlice(slices) will return Tuple(slices, Load()). (Contributed by Serhiy Storchaka in bpo-34822.)
The second patch is still a work-in-progress, for two reasons: I don't know if the bit I added is functionally correct (though it resolves 20/24 of the test failures), and I don't know how to handle `ast.Call` (and potentially anything else) that seems to be the cause of the remaining 4 failures.
Help required.
[1] https://docs.python.org/3/whatsnew/3.9.html#changes-in-the-python-api
=> Python 3.9 ast changes

rope/base/default_config.py
In the spirit of #324  I could verify that long waiting times are a result of not ignoring `venv` or `.venv` (pick your poison). As it is best practice to use venv I think they should be ignored by default. Also this cost me way to much headache to realize and I can imagine  that I am not alone in that regard.
Greetings,
Leon
=> Modifies default_config.py

README.rst, docs/contributing.rst
As of the time of posting, the developer's Google Group seems to be dead. Unless someone has the know-how and ability to restore the Google Groups mailing list and take ownership to manage it, then it would make sense to just abandon it and do all dev discussion in Github.
Should we just move completely to Github? Maybe enable Github Discussions for the repository?
This Pull Request does not constitute a decision to abandon the mailing list. If we decide to continue with the mailing list, then this pull request should be closed.
=> Discuss: should we move off the Google Groups developer mailing list to Github?

rope/refactor/extract.py, rope/refactor/similarfinder.py, rope/refactor/usefunction.py, ropetest/refactor/extracttest.py
=> Support extract method of expressions with inline assignment (walrus operator)

rope/refactor/patchedast.py, ropetest/refactor/extracttest.py, ropetest/refactor/patchedasttest.py
Original patch was created by @ceridwen, thank you for your contribution!
The original patch looks good, this PR just made minor cleanup and added some tests.
Fix #117.
Close #126.
=> Fix MismatchedTokenError caused by use of exec with parentheses in Python 2

rope/refactor/importutils/module_imports.py, ropetest/refactor/importutilstest.py, ropetest/testutils.py, setup.py
=> Don't remove values listed in __all__ when organizing imports

rope/refactor/extract.py, ropetest/refactor/extracttest.py
=> Fix variables that are returned and/or turned into argument when extracting method in a loop

rope/refactor/extract.py, rope/refactor/patchedast.py, ropetest/refactor/extracttest.py, ropetest/refactor/patchedasttest.py
=> Implement `async def`, `async for`, and `await` syntax for method extraction

CHANGELOG.md, rope/refactor/extract.py, ropetest/refactor/extracttest.py
Very similar to the case resolved in #391 by @climbus, but for index
assignment instead of attribute assignment.
=> Extract with assignment for index assignment

.all-contributorsrc, CHANGELOG.md, CONTRIBUTORS.md, rope/base/codeanalyze.py, rope/base/simplify.py, ropetest/refactor/inlinetest.py, ropetest/simplifytest.py
=> Fix inlining into f-string containing quote characters

CHANGELOG.md, rope/base/pyobjects.py, rope/base/pyobjectsdef.py, rope/base/pyscopes.py, rope/base/utils/__init__.py, ropetest/pyscopestest.py
Added scope for comprehension expressions
Part of https://github.com/python-rope/rope/issues/293
- [ x] I have added tests that prove my fix is effective or that my feature works
- [ x] I have updated CHANGELOG.md
=> Comprhensions with scope

rope/base/pyobjectsdef.py, ropetest/pyscopestest.py
In rope master, code that uses inline assignment (`:=` operator), doing a AutoImport.generate_cache() produces an error:
```
Traceback (most recent call last):
File "ref.py", line 8, in <module>
importer.generate_cache()
File "/home/user/rope/rope/contrib/autoimport.py", line 107, in generate_cache
self.update_resource(file, underlined)
File "/home/user/rope/rope/contrib/autoimport.py", line 160, in update_resource
self._add_names(pymodule, modname, underlined)
File "/home/user/rope/rope/contrib/autoimport.py", line 183, in _add_names
attributes = pymodule._get_structural_attributes()
File "/home/user/rope/rope/base/utils/__init__.py", line 32, in newfunc
return func(self, *args, **kwds)
File "/home/user/rope/rope/base/pyobjects.py", line 179, in _get_structural_attributes …
```
=> Fix error "'_ExpressionVisitor' object has no attribute 'defineds'"

CHANGELOG.md, rope/refactor/patchedast.py, ropetest/refactor/patchedasttest.py, ropetest/refactor/restructuretest.py
Implement `yield from` syntax for restructuring and extraction.
=> Implement `yield from` syntax into patchedast

CHANGELOG.md, rope/refactor/patchedast.py, ropetest/refactor/patchedasttest.py
Improve handling of empty tuple and handling of parentheses around tuple by patchedast. Previously, these cases would've caused MismatchedTokenError.
=> Improve empty tuple and handling of parentheses around tuple

rope/refactor/patchedast.py, ropetest/refactor/patchedasttest.py
Improve handling of empty tuple and handling of parentheses around tuple by patchedast. Previously, these cases would've caused MismatchedTokenError.
=>  Improve empty tuple and handling of parentheses around tuple (Pt. 2)

CHANGELOG.md, rope/base/change.py, rope/base/fscommands.py, rope/base/pyobjectsdef.py, rope/base/resources.py, ropetest/projecttest.py
If a file is not using local line ending, then we write it back into the same line ending format.
Fixes #134
=> Preserve newline format when writing files

CHANGELOG.md, rope/refactor/extract.py, ropetest/refactor/extracttest.py
Fix an error when extracting a method containing list comprehension with multiple targets:
```python
mylist = [(a, b) for a, b in lst]
```
produces an error:
```
AttributeError: 'Tuple' object has no attribute 'id'
```
=> Fix extract info collection for list comprehension with multiple targets

CHANGELOG.md, rope/refactor/extract.py, ropetest/refactor/extracttest.py
Previously, we always join lines when extracting one-line expression, this leads to absurdly long lines when extracting large expressions, like dictionary definitions. With this PR, we improve the heuristic so larger multiline expressions can stay multiline after extraction while smaller expressions are joined together.
=> Improve the heuristic for joining lines when extracting one line expression

CHANGELOG.md, rope/refactor/extract.py, ropetest/refactor/extracttest.py
=> Support for augmented assignment to subscript inside try..except block

CHANGELOG.md, rope/base/worder.py, ropetest/refactor/inlinetest.py
fix(inline): Inlining methods with type hints in signature
Fixes #440
=> fix(inline): Inlining methods with type hints in signature

CHANGELOG.md, rope/base/pyobjectsdef.py, ropetest/refactor/extracttest.py
Fixed extracting method from class method when there is list comprehension inside method.
Fixes #461
=> fix(extract-method): Extracts method when list comprehension within method's scope

rope/contrib/autoimport/sqlite.py
The change in 89341d4742ac2414051fd671acad8ad48eb9ccf6 broke backward compatibility because it changed what `AutoImport.project` refers to. It was a rope Project but that commit changed it into an autoimport Package.
This PR puts the `.project` back to where it was originally.
=> Rename AutoImport.rope_project back to AutoImport.project

rope/base/utils/pycompat.py, rope/contrib/autoimport/sqlite.py
On windows, the python sys.path includes random files. I do not have windows and 100% of development is on linux but it failed on pylsp's CI. I filtered out files from the search, but cannot easily test this code. I am also unsure of why files are included in sys.path on windows. 
autoimport on windows.
=> Fix windows

CHANGELOG.md, rope/base/taskhandle.py, rope/contrib/autoimport/sqlite.py
Introduces a base task handle (and job set) class. I noticed that NullTaskHandle and TaskHandle did not provide identical APIs so I used ABC base classes to do so. I also created a method to increment the count of a job set for autoimport and used that.
This will break any jobsets which didn't match the TaskHandle API.
Since the increment method is abstract, it will break jobsets without it as well. I can make it non-abstract but that seems like bad practice.
=> introduce task handle base class

rope/base/taskhandle.py
Prevents issues where name or job_name isn't defined such as null task handle
Can probably count as part of the task_handle ABC class.
=> add default values for name/job_name properties

.github/workflows/main.yml, rope/base/fscommands.py, rope/base/oi/runmod.py, rope/base/oi/type_hinting/evaluate.py, rope/base/oi/type_hinting/utils.py, rope/base/pyobjectsdef.py, rope/base/stdmods.py, rope/base/utils/__init__.py, rope/base/utils/pycompat.py, rope/refactor/occurrences.py, rope/refactor/patchedast.py, rope/refactor/suites.py, ropetest/advanced_oi_test.py, ropetest/refactor/patchedasttest.py, setup.py
Dropping Python 2 support.
This is part of cherry picking parts of bageljrkhanofemus' commits in https://github.com/python-rope/rope/pull/473 so that PR would be easier to review.
=> Drop python2 specific code

CHANGELOG.md, rope/refactor/importutils/module_imports.py, ropetest/refactor/importutilstest.py
Support more cases of value inferences
=> Improved value inference of __all__ declaration

CHANGELOG.md, rope/base/project.py, rope/base/pyobjects.py, rope/base/pyobjectsdef.py, rope/base/resources.py, ropetest/reprtest.py
Add some `__repr__`
Fixes #197
=> Add some basic __repr__ to make it easier for debugging

.gitignore, .readthedocs.yaml, docs/Makefile, docs/conf.py, docs/configuration.rst, docs/index.rst, docs/make.bat, docs/release-process.rst, setup.py
This is cherry-picking readthedocs-related changes from #473.
=> use read the docs and sphinx

docs/overview.rst, rope/base/builtins.py, rope/contrib/autoimport/sqlite.py, rope/refactor/change_signature.py, rope/refactor/occurrences.py, ropetest/codeanalyzetest.py
There are small typos in:
- docs/overview.rst
- rope/base/builtins.py
- rope/contrib/autoimport/sqlite.py
- rope/refactor/change_signature.py
- rope/refactor/occurrences.py
- ropetest/codeanalyzetest.py
Fixes:
- Should read `tries` rather than `trys`.
- Should read `predicate` rather than `prediate`.
- Should read `occurrences` rather than `occurences`.
- Should read `concatenated` rather than `cancatenated`.
- Should read `applied` rather than `applyed`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: Fix a few typos

CHANGELOG.md, rope/refactor/patchedast.py, ropetest/refactor/patchedasttest.py
Fix issue with parsing code with MatMul operator.
Fixes #496
=> Add MatMul operator to patchedast

.gitignore, CHANGELOG.md, rope/contrib/autoimport/sqlite.py
Faster implementation, some refactoring,
=> Autoimport improvements

CHANGELOG.md, rope/contrib/autoimport/models.py, rope/contrib/autoimport/sqlite.py, ropetest/contrib/autoimport/modeltest.py
Add a minimal database wrapper and query generator. This is to avoid doing string manipulations on SQL code, enforcing use of parameterized query.
=> Add autoimport database wrapper

CHANGELOG.md, rope/refactor/extract.py, ropetest/refactor/extracttest.py
Extracting generator comprehension without selecting the surrounding parentheses may produce invalid code. This commit adds surrounding parentheses when it detects that the selected code is a bare generator comprehension.
Fixes #411
=> Fix extracting generator without parens

CHANGELOG.md, rope/base/evaluate.py, rope/base/oi/type_hinting/utils.py, rope/base/pycore.py, ropetest/refactor/renametest.py
When the function is a builtin function, the call parameter's name was sometimes incorrectly identified as an AssignedName. This led to rename refactoring incorrectly renaming these parameters.
Fixes #18
=> Fix #18. Identify AbstractFunction parameters as ParameterName

CHANGELOG.md, docs/configuration.rst, pyproject.toml, rope/base/prefs.py
Global config support
Fixes #(issue)
#243
=> global configuration

CHANGELOG.md, rope/refactor/extract.py, ropetest/refactor/extracttest.py
`_AugAssign` now recursively walk the left hand expression (i.e. node.target) for it to handle these more complex expressions.
Fixes #509
=> Fix read/write analysis of the left-hand side of an augmented assignment

CHANGELOG.md, rope/refactor/patchedast.py, ropetest/refactor/patchedasttest.py
Somehow, this was missed back when the rest of `match` statement was implemented.
Fixes #522
=> Fix #522. Implement patchedast parsing of MatchMapping

CHANGELOG.md, pyproject.toml, pytest.ini
Replaces #450 and #519
Closes #414
Thanks @gliptak and @bagel897 for helping with this change.
=> Migrate pytest.ini to pyproject.toml

CHANGELOG.md, rope/refactor/inline.py, rope/refactor/sourceutils.py, ropetest/refactor/inlinetest.py
Retain multiline expressions when inlining. Previously, we'd try to join the lines, which is rarely desirable. The new behavior preserves original code's formatting as much as possible.
Fixes #514
=> Fix #514. Fix multiline inline

rope/base/ast.py, rope/base/change.py, rope/base/fscommands.py, rope/base/pyobjects.py, rope/base/pyobjectsdef.py, ropetest/contrib/codeassisttest.py
These are cleanup of remnants of code from the Python 2 -> 3 transition.
=> Remove usage of `unicode` type

ropetest/refactor/patchedasttest.py
Credit to @edreamleo for finding this issue as part of his #540.
=> Remove unused vars

rope/base/ast.py
The walk function should not appear to return a value.
The legacy code generates (valid) errors from pylint and mypy.
=> Clean the walk function in rope.base.ast

setup.cfg
=> Add config file for linters

rope/refactor/extract.py, ropetest/refactor/extracttest.py
See #553. This PR could be called an emergency fix.
flake8 reported the error. Unit tests did not.
Still unresolved: creating a unit test that should have failed :-)  See #545, which suggest better test coverage.
=> PR for #553: Fix potential crasher in _getarguments

CHANGELOG.md, rope/refactor/patchedast.py, ropetest/refactor/patchedasttest.py
=> Fix #559 Whitespace around import statements

CHANGELOG.md, rope/base/ast.py, rope/base/astutils.py, rope/base/evaluate.py, rope/base/oi/soa.py, rope/base/pyobjects.py, rope/base/pyobjectsdef.py, rope/base/pyscopes.py, rope/contrib/finderrors.py, rope/refactor/extract.py, rope/refactor/importutils/module_imports.py, rope/refactor/patchedast.py, rope/refactor/restructure.py, rope/refactor/similarfinder.py, rope/refactor/suites.py, rope/refactor/usefunction.py
- Remove `rope.base.ast.walk()`
- Remove `rope.base.ast.get_children()`
- Remove `rope.base.ast.get_child_nodes()`
=> Remove functions in rope.base.ast that has functionally identical implementation in stdlib's ast

rope/base/pynames.py
This PR undoes the useless comments re annotations in pynames.py that sneaked in recently.
These comments might well confuse or annoy devs who understand how to use postponed annotations, [PEP 563](https://peps.python.org/pep-0563/).
=> PR: Remove useless/confusing comments re stdlib.annotations

ropetest/codeanalyzetest.py, ropetest/pycoretest.py, ropetest/pyscopestest.py, ropetest/refactor/extracttest.py, ropetest/refactor/importutilstest.py, ropetest/refactor/patchedasttest.py, ropetest/refactor/renametest.py
Python 3.6 and below have reached the end of their lifetimes.
=> PR Remove 'only_for' decorator for all python versions less than 3.7

CHANGELOG.md, rope/base/project.py, ropetest/projecttest.py, ropetest/testutils.py
- Remove redundant testutils.sample_project(ropefolder) arguments
- Simplify implementation of sample_project()
- Remove root argument
- Change testutils.py to use pathlib
- Rewrite test that creates errant sample_folder directory
- Remove unnecessary remove_recursively() when creatings sample_project()
Fixes #589
=> Fix #589 Cleanup testutils.sample_project()

CHANGELOG.md, ropetest/projecttest.py
Fix test that sometimes leaves files behind in the current working directory
Also, convert the test to pytest style test since the test was essentially re-written from scratch anyway.
=> Fix test that sometimes leaves files behind in the current working directory

CHANGELOG.md, docs/configuration.rst, docs/default_config.py, rope/base/history.py, rope/base/oi/memorydb.py, rope/base/prefs.py, rope/base/project.py, rope/contrib/findit.py, ropetest/projecttest.py, ropetest/reprtest.py
Remove compress_objectdb and compress_history config. These day and age, compressing these files are just negligible savings in disk space. 
This simplifies the DataFile mechanism in preparation for #605.
=> Remove .ropeproject/history and .ropeproject/objectdb compression

CHANGELOG.md, rope/base/history.py, rope/base/oi/memorydb.py, rope/base/project.py
Remove compress_objectdb and compress_history config. Rope has never generated these files for a very long time, it's very unlikely someone still have a data file from ten years ago and want to open them.
This simplifies the DataFile mechanism in preparation for https://github.com/python-rope/rope/issues/605.
=> Remove _DataFiles._import_old_files()

rope/base/project.py
Another pyflakes complaint that can't be turned off:
```console
project.py:2:1: 'shutil' imported but unused
```
=> PR: Remove pyflakes complaint about an unused import

rope/refactor/patchedast.py
We all know the pattern:
```python
except SomeException as e:
...
```
In this case, however, `e` isn't used. The existing code adds a `# noqa` comment, but there is no way to turn off the pyflakes complaint:
```console
patchedast.py:925:9: local variable 'e' is assigned to but never used
```
Imo, there is no need to fussily add the `as e:  # noqa`. 
@lieryan I'll be happy to add any comment you like just below the changed line.
=> PR: Remove a pyflakes nit and a flake8 suppression

rope/base/builtins.py
@lieryan This PR is experimental. Your comments, please.
`rope.base.builtins` contains an attempted import of `raw_input`, which exists only in Python2.
The PR suggests using `input` instead, including as a dictionary key.
All tests pass, but I don't really understand this code.
=> PR: Remove python2 metion of raw_input

rope/refactor/occurrences.py
pyflakes complained (correctly) that the import of pynamesdef was not used.
=> Remove unused import in occurrences.py

rope/refactor/patchedast.py
Some refactoring.
It should not change any behavior. (perhaps a tiny bit faster )
=> Refactor patchedast

CHANGELOG.md, docs/library.rst, rope/refactor/patchedast.py, ropetest/refactor/extracttest.py, ropetest/refactor/patchedasttest.py
Remove code for old ast nodes for syntaxes that are no longer supported by Python 3.7 and upwards.
=> Remove support for deprecated ast nodes

rope/base/builtins.py, ropetest/contrib/codeassisttest.py
See #616.
[x] - Remove 'file' from builtins.
[x] - Remove completions test for 'file'.
[x] - Add completions test for 'open'
=> PR for #616: failing unit test after removing 'file' from rope.base.builtins

CHANGELOG.md, rope/refactor/patchedast.py, ropetest/refactor/patchedasttest.py
Python 3 no longer supports the `01234` syntax for specifying octal literals (it raises a syntax error), now you have to use `0o1234`.
=> Fix parsing of octal literal by patchedast

CHANGELOG.md, rope/base/versioning.py, ropetest/conftest.py, ropetest/contrib/autoimport/conftest.py, ropetest/versioningtest.py
Add a method to calculate version hash that will eventually be used to version autoimport.db for auto-detecting whether we need to refresh the cached data. 
Note that this PR hadn't implemented storing the version_hash into the metadata table in autoimport.db yet. 
Part of patch series #565
=> Implement version hash

CHANGELOG.md, rope/base/ast.py, rope/refactor/patchedast.py, rope/refactor/similarfinder.py, ropetest/refactor/patchedasttest.py
This PR consists of only this commit from edreamleo:
- [Remove 'recursive' kwarg to call_for_nodes and simplify](https://github.com/python-rope/rope/pull/633/commits/bb5f312ba9e12b1cea82e926f6f3e60b819dbe59)
=> Remove call_for_nodes(recursive) argument 

README.rst
Readme talked about dropping python 2 support in 1.0 in future tense, but 1.0 is actually out for a long time
=> Update readme to reflect 1.0 has been released.

rope/base/ast.py, ropetest/refactor/patchedasttest.py
This is useful for the tests, that benefits from the more granular identification, making the test cases a bit more readable than if everything is an `ast.Constant`.
=> Add a function to identify ast Constant nodes more granularly

rope/contrib/generate.py
A nit, discovered while investigating the unit test framework. The eval does not seem like a security problem :-)
The new code does, however, reinforce the docstring.
Hmm. `create_generate` does not appear anywhere in Rope except for the two unit tests that test it. Nor do the docs mention `create_generate`. What's going on?
=> PR: remove unnecessary eval in generate.py

rope/base/ast.py, rope/refactor/similarfinder.py, ropetest/refactor/patchedasttest.py
Per the discussion in PR #633.
=> PR: Add comments & docstrings related to call_for_nodes

rope/contrib/generate.py
Per [this comment](https://github.com/python-rope/rope/pull/640#issuecomment-1370455862).
=> PR: Add type annotations for rope.contrib.generate.create_generate()

rope/refactor/patchedast.py, ropetest/refactor/patchedasttest.py
Fixes #435
I am not sure if this is the "correct" thing to do here, but it fixes the test case and doesn't break any others.
When run against our internal python codebase (~3500 files) it produces no errors anymore.
=> Fix fstrings with mismatched parens

rope/refactor/importutils/__init__.py, ropetest/refactor/importutilstest.py
When converting from imports on a large codebase I encountered many files that failed with errors of the form:
```
Syntax error in file <foo.py> line <123>: expression cannot contain assignment, perhaps you meant "=="?
```
This was traced back to erroneously renaming keyword arguments that conflicted with renamed imports, resulting in code that looked something like the following:
Before
```python
from os import path
foo(path=path.join('a', 'b'))
```
After
```python
import os
foo(os.path=os.path.join('a', 'b'))
```
=> Fix renaming kwargs when refactoring from imports

rope/base/oi/doa.py, rope/base/oi/runmod.py, rope/base/oi/type_hinting/evaluate.py, rope/base/oi/type_hinting/providers/docstrings.py, rope/base/oi/type_hinting/resolvers/types.py, rope/base/oi/type_hinting/utils.py, rope/base/pycore.py, rope/base/stdmods.py, rope/contrib/generate.py, rope/refactor/extract.py, rope/refactor/importutils/importinfo.py, rope/refactor/inline.py
GitHub tests will fail with code formatted with previous versions of black.
=> PR: Reformat using black 23.1.0

CHANGELOG.md, rope/base/ast.py, rope/base/fscommands.py, rope/base/oi/doa.py, rope/base/oi/runmod.py, rope/base/oi/type_hinting/evaluate.py, rope/base/oi/type_hinting/providers/numpydocstrings.py, rope/base/oi/type_hinting/utils.py, rope/base/prefs.py, rope/base/project.py, rope/base/pyobjects.py, rope/contrib/autoimport/sqlite.py, rope/refactor/extract.py, rope/refactor/importutils/importinfo.py, rope/refactor/move.py
**Summary**
This PR contains the *minimum* changes (to the `master` branch) needed to fix and suppress all mypy complaints *without* removing the wildcard import in `rope.base.ast`.
This PR:
- Shows that mypy is not adversely affected by the wildcard import in `rope.base.ast`!!
- Suppresses all mypy complaints, mostly with `# type: ignore` comments.
Comments describe all interesting/unusual suppressions.
- Adds two missing base-class methods whose absence rightly generated mypy errors.
**Details**
- Add `# type: ignore` as needed to suppress warnings about optional imports.
- **rope.base.ast**: mypy rightly complains about an import, but this import does not mypy significantly!
- **rope.base.oi.type_hinting.evaluate**: Suppress complaints about functions decorated with `@multi`.
- …
=> PR: Fix/suppress all mypy complaints (based on master)

rope/base/oi/soi.py
The `then-clause` of an `if` statement was `pass`.
=> PR: Remove a do-nothing statement in soi._handle_first_parameter

CHANGELOG.md, rope/contrib/autoimport/utils.py, ropetest/contrib/autoimport/utilstest.py
Change glob pattern in get_files() to scan site-packages recursively.
Fixes #687
=> Fix autoimport not scanning packages recursively

docs/library.rst, rope/contrib/autoimport/models.py, rope/contrib/autoimport/sqlite.py, ropetest/contrib/autoimport/autoimporttest.py
Add metadata table to the autoimport database.
Also, this deprecates the default value for `AutoImport(memory)` parameter, as the default value is going to change in the future.
Fixes #565
=> Add metadata table to Autoimport database

.github/workflows/main.yml, CHANGELOG.md, pyproject.toml, rope/base/pyobjects.py, rope/refactor/importutils/module_imports.py, ropetest/codeanalyzetest.py
Fixes to support Python 3.12.
Fixes #708
=> Add support for Python 3.12

CHANGELOG.md, rope/refactor/patchedast.py, ropetest/refactor/extracttest.py, ropetest/refactor/patchedasttest.py
Python 3.11 added exception groups using the `except*` syntax. This PR adds the patchedast for handling this syntax.
Fixes #561
=> Implement `except*` syntax

CHANGELOG.md, docs/conf.py
This patch allows build documentation without have `rope` module installed by execute `sphinx-build -n -T -b <output_format> docs`. This patch does exactly what is described in comment above.
=> allow build documenatation without have rope module installed

CHANGELOG.md, rope/contrib/autoimport/sqlite.py, ropetest/conftest.py, ropetest/contrib/autoimport/autoimporttest.py
Addresses https://github.com/python-rope/rope/pull/714#issuecomment-1784018856, using a threadlocal to create data base connections.
Fixes #713
=> Create one database connection per thread

CHANGELOG.md, rope/contrib/autoimport/sqlite.py, ropetest/conftest.py, ropetest/contrib/autoimport/autoimporttest.py
As discussed in https://github.com/python-rope/rope/pull/714#issuecomment-1783791890, this PR sets the foundation for using `AutoImport` in a multithreading environment by using an in-memory database with shared cache per `Project` if `memory=True`. On-disk databases are not affected.
=> Use in-memory database with shared cache

CHANGELOG.md, rope/contrib/autoimport/sqlite.py, rope/contrib/autoimport/utils.py
Remove `site-packages` from the python package search tree to avoid duplicate entries in the autoimport database. This also speeds up generating the modules cache by a factor of ~2.
Fixes #722
=> Remove site-packages from packages search tree

CHANGELOG.md, rope/base/resources.py, rope/contrib/autoimport/sqlite.py, ropetest/projecttest.py
This is a step towards implementing #562.
=> Implement os.PathLike on Resource

CHANGELOG.md, rope/contrib/autoimport/models.py, ropetest/contrib/autoimport/autoimporttest.py
The regular indexes are needed for searching exact matches. This PR adds a nocase index to allow doing prefix search using the LIKE query.
Fixes #736
=> Ensure autoimport requests uses indexes 

CHANGELOG.md, rope/refactor/extract.py, rope/refactor/sourceutils.py, ropetest/refactor/extracttest.py
Raise exception when extracting the start of a block without the end, examples in the issue and the included tests.
Fixes #734
The added logic is:
* Raise when:
* region end is more indented than region start, AND
* the next line after region end is indented as much as region end or more.
* When any of these (start, end, or next) are on a blank/comment line, consider the next "real" line instead.
This seems correct to me and passes existing tests, but it could use a look by someone familiar with this part of the code to make sure it makes sense and is following conventions.
=> Add error handling for extract of incomplete block

CHANGELOG.md, rope/refactor/rename.py, ropetest/refactor/renametest.py
Please include a summary of the change and which issue is fixed.
Fixes #698
=> add validation to refuse Rename refactoring to a python keyword

rope/contrib/autoimport/sqlite.py
=> Minor type hint improvements

.github/workflows/main.yml, CHANGELOG.md, rope/contrib/generate.py, rope/refactor/functionutils.py, ropetest/refactor/inlinetest.py
Worder had so many parsing issues with new Python function features.
=> Improved function parser to use ast parser instead of Worder

.github/workflows/main.yml, README.rst, pyproject.toml
Add codecov when running in GHA
=> Create code coverage when running pytest in GHA

CHANGELOG.md, ropetest/conftest.py, ropetest/contrib/autoimport/conftest.py, ropetest/contrib/autoimporttest.py
Isolate tests that uses external_fixturepkg into a venv
This avoids modifying the test runtime environment itself.
Fixes #781
=> Isolate tests that uses external_fixturepkg into a venv

CHANGELOG.md, pyproject.toml, rope/contrib/generate.py, rope/refactor/move.py, ropetest/refactor/movetest.py
Some refactoring on movetest.py, adding type hints, and misc.
=> Refactor movetest.py

.github/workflows/black.yml, .github/workflows/codeql.yml, .github/workflows/main.yml, CHANGELOG.md
Fixes Github Actions warning of using outdated Nodejs versions:
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-python@v4. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
=> Update github workflows

CHANGELOG.md, pyproject.toml, rope/refactor/importutils/importinfo.py, ropetest/reprtest.py
- Add __repr__ to ImportInfo
- Add type hints to importinfo.py
=> Add type hints to importinfo.py and add repr to ImportInfo

docs/library.rst
The docs on refactoring mention a `Move` class that doesn't exist in the current codebase. This changes it to `create_move` which does exist and matches the signature of the supposed `Move` class.
Fixes #794
=> Fix mention of Move -> create_move in docs

CHANGELOG.md, docs/configuration.rst, docs/default_config.py, rope/base/prefs.py, rope/refactor/importutils/__init__.py, ropetest/refactor/importutilstest.py, ropetest/refactor/movetest.py
Added a new setting (`imports.preferred_import_style`) that controls how rope inserts new import statements.
It can be set to:
- `normal-import` (default) which will insert imports as `import <package>`
- `from-module` which will insert imports as `from <package> import <module>`
- `from-global` which will insert imports as `from <package>.<module> import <object>`
Credit: the solution here is based on [nicoolas25](https://github.com/nicoolas25)'s work on #696, but implements the config settings in a slightly different way.
=> Implement preferred_import_style

.github/workflows/main.yml, .readthedocs.yaml, rope/base/oi/type_hinting/utils.py, rope/contrib/autoimport/sqlite.py, rope/contrib/autoimport/utils.py, rope/refactor/importutils/module_imports.py
=> Update GHA Python versions

rope/base/oi/type_hinting/utils.py, rope/contrib/autoimport/sqlite.py
- python 3.13 removed `collections/abc.py`, update the `deprecated_aliases` variable for this case
- python 3.13 raises `PermissionError` earlier on initialization of the `iterdir()` instead of just on `next()`
Fixes #801
=> Python3.13 compat

rope/base/ast.py
As of Python 3.14 `ast` will lack `_const_node_type_names`.
Close #810
=> Adapt conditional for Python 3.14
