python-rope/rope

rope/base/project.py

While looking at #109, I was digging into what `_realpath` is about and I thought it to be worthy to preserve this explanation.
@aligrudi , what do you think?

Add a little explanation of what _realpath function is about.

---

.travis.yml
rope/base/ast.py
rope/base/builtins.py
rope/base/change.py
rope/base/codeanalyze.py
rope/base/fscommands.py
rope/base/oi/doa.py
rope/base/oi/memorydb.py
rope/base/oi/objectdb.py
rope/base/oi/runmod.py
rope/base/project.py
rope/base/pyobjectsdef.py
rope/base/resources.py
rope/contrib/codeassist.py
rope/contrib/fixsyntax.py
rope/refactor/change_signature.py
rope/refactor/importutils/module_imports.py
rope/refactor/inline.py
rope/refactor/patchedast.py
rope/refactor/similarfinder.py
ropetest/advanced_oi_test.py
ropetest/contrib/codeassisttest.py
ropetest/projecttest.py
ropetest/pycoretest.py
ropetest/refactor/change_signature_test.py
ropetest/refactor/patchedasttest.py
ropetest/testutils.py
setup.py

I realise that some others may have done some work in this direction cc #57.
This changes syntax and imports so that python at least runs (while tests continue to pass in python 2).

Initial work towards python 3

---

rope/refactor/extract.py
ropetest/refactor/extracttest.py

* add tests
* all test passed
* works correctly

fixed extracting for ... else block to method

---

ropetest/refactor/extracttest.py

Fix formatting and remove TABs.

---

rope/refactor/patchedast.py
ropetest/refactor/patchedasttest.py

http://greentreesnakes.readthedocs.io/en/latest/nodes.html#Call

support for starredargs and keywords in 3.5

---

docs/overview.rst
rope/base/oi/soi.py
rope/base/oi/type_hinting/factory.py
rope/base/oi/type_hinting/interfaces.py
rope/base/oi/type_hinting/providers/composite.py
rope/base/oi/type_hinting/providers/docstrings.py
rope/base/oi/type_hinting/providers/inheritance.py
rope/base/oi/type_hinting/providers/interfaces.py
rope/base/oi/type_hinting/providers/pep0484_type_comments.py
rope/base/oi/type_hinting/utils.py
ropetest/type_hinting_test.py

Now we have only 3 types of provider.

#189 Inline IAttrProvider into IAssignmentProvider

---

rope/contrib/generate.py
ropetest/contrib/generatetest.py

It adds ability to generate class in module other than current.

Generating class in other module.

---

setup.py

This is a replacement for lost #210.

fix installation issue on windows

---

rope/base/builtins.py
ropetest/builtinstest.py

Fix for incorrent parent on builtin function

---

COPYING
rope/__init__.py
setup.py

Fixes #262
Please, review and comment swiftly.

Relicensing to LGPLv3+

---

rope/base/project.py

Fix simple typo: sitaution -> situation

---

.travis.yml
rope/base/change.py
rope/base/evaluate.py
rope/base/libutils.py
rope/base/oi/__init__.py
rope/base/oi/objectdb.py
rope/base/oi/soi.py
rope/base/oi/transform.py
rope/base/project.py
rope/base/pynames.py
rope/base/pyobjects.py
rope/base/resourceobserver.py
rope/base/resources.py
rope/base/utils/datastructures.py
rope/contrib/autoimport.py
rope/contrib/codeassist.py
rope/contrib/finderrors.py
rope/contrib/findit.py
rope/refactor/change_signature.py
rope/refactor/encapsulate_field.py
rope/refactor/importutils/__init__.py
rope/refactor/importutils/actions.py
rope/refactor/introduce_factory.py
rope/refactor/move.py
rope/refactor/rename.py
rope/refactor/restructure.py
ropetest/advanced_oi_test.py
ropetest/contrib/codeassisttest.py

Make rope compatible with Python 3.8

---

.travis.yml
rope/base/change.py
rope/base/evaluate.py
rope/base/libutils.py
rope/base/oi/__init__.py
rope/base/oi/objectdb.py
rope/base/oi/soi.py
rope/base/oi/transform.py
rope/base/project.py
rope/base/pynames.py
rope/base/pyobjects.py
rope/base/resourceobserver.py
rope/base/resources.py
rope/base/utils/datastructures.py
rope/contrib/autoimport.py
rope/contrib/codeassist.py
rope/contrib/finderrors.py
rope/contrib/findit.py
rope/refactor/change_signature.py
rope/refactor/encapsulate_field.py
rope/refactor/importutils/__init__.py
rope/refactor/importutils/actions.py
rope/refactor/introduce_factory.py
rope/refactor/move.py
rope/refactor/rename.py
rope/refactor/restructure.py
ropetest/advanced_oi_test.py
ropetest/contrib/codeassisttest.py

284 python38

---

rope/base/worder.py
ropetest/codeanalyzetest.py

Hello, this fixes #202 at least on my project. Let's see if tests pass

Fix relative import offset calculation

---

rope/base/pynamesdef.py

This seems to fix #260 for me. I don't know how to put a test since I couldn't manage to understand what was causing it.

Fix AttributeError lineno

---

CHANGELOG.md
rope/base/pyscopes.py
ropetest/pyscopestest.py

get_holding_scope_for_offset gets scope by offset not a line

---

.github/workflows/main.yml
CHANGELOG.md
ropetest/testutils.py

Add Python 3.10 to Github Action

Add Python 3.10 to Github Action test

---

CHANGELOG.md
rope/base/utils/pycompat.py
rope/refactor/extract.py
rope/refactor/patchedast.py
rope/refactor/suites.py
ropetest/refactor/extracttest.py
ropetest/refactor/patchedasttest.py
ropetest/refactor/suitestest.py

Implement `match` and `case` statement.
Fixes #451

Implement #451 structural pattern matching

---

.github/workflows/main.yml
CHANGELOG.md
README.rst
pyproject.toml
rope/__init__.py
setup.py

Drop Python 2.7 support
Fixes #400

Drop Python 2.7 support

---

CHANGELOG.md
rope/refactor/importutils/module_imports.py
rope/refactor/move.py
ropetest/refactor/movetest.py

fix(move): Moves decorated function or class to other module

---

CHANGELOG.md
rope/contrib/autoimport/utils.py
ropetest/contrib/autoimport/conftest.py
ropetest/contrib/autoimport/utilstest.py

Fixes #495 test failing due to `zlib` not being compiled in some systems

---

rope/contrib/autoimport/sqlite.py

slight performance improvement

executemany

---

rope/contrib/findit.py

The fourth and last PR in this round of cleanups.
Other pyflakes complaints may disappear later as part of new PRs.

PR: pyflakes nit 4: unused var

---

rope/base/oi/soa.py

The first of several PRs removing pyflakes complaints.
I'll only submit PRs for complaints that clearly can be fixed without impacting Rope in any way.

PR: pyflakes nit1: redefinition of unused '_follow'

---

CHANGELOG.md
rope/contrib/autoimport/models.py
ropetest/contrib/autoimport/modeltest.py

SQLite models improvements

---

docs/contributing.rst

See title. Encountered this when following https://rope.readthedocs.io/en/latest/contributing.html.
Fixes #718

Correct typo for development install
